name: 自动部署
on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 安装依赖
      run: echo "不需要安装，纯HTML项目"
      
    - name: 性能测试
      uses: treosh/lighthouse-ci-action@v9
      with:
        urls: https://kurinabluu.github.io/Project_Web1204/index.html
        uploadArtifacts: true
